# -*- coding: utf-8 -*-
"""heart_data_visualization_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jxeihvPJ7BF5cNd_4-8WRUMntn85xqI8
"""

pip install pygwalker

import pandas as pd
df=pd.read_csv("/content/heart.csv")
df

import pygwalker as pyg
pyg.walk(df)